### ISSUE TITLE
Modify code to handle run error when examples, log directories are not under running directory

### ISSUE THREAD

**Issue by Emily2015** [inferno-community/dynamic-example-information#4]
Nice work! Noticed one minor thing:

1. I did a pull first to get the latest code

2.  Per README.md, I ran the following command:
 rake fhir_gen:run[uscore,2,max]

It failed (please see  below "5. Initial Run Errors" section for more details) while trying to access **examples** and **log** dirs.  Therefore, I ran "mkdir examples" and "mkdir log" under dynamic-example-information dir.  I was able to run the script and it successfully created files under examples and log dirs after that.

3. Suggested changes to code: since mkdir on line 130 and 151 of lib/structure_definition.rb does not recursively create all parent directories of the directory you want to create, an error is thrown. To fix this, you could use FileUtils.mkdir_p, which does create all parent directories. 

4. Current line 130 and line 151 code in dynamic-example-information/lib/structure_definition.rb script:
....
    **130       Dir.mkdir("examples/#{@ig_name}") unless File.exist?("examples/#{@ig_name}")**
    131       File.open("examples/#{@ig_name}/#{@example_num}_#{@resource_id}.json", "w+") do |f|
    .....
    150     def write_failure_log
    **151       Dir.mkdir("log/#{@ig_name}") unless File.exist?("log/#{@ig_name}")**

5. Initial Run Errors:

[emily@delli5 dynamic-example-information]$ rake fhir_gen:run[uscore,2,max]
Generating 60 examples across 30 uscore resources using max cardinality strategy...

rake aborted!
Errno::ENOENT: No such file or directory @ dir_s_mkdir - examples/uscore
/home/emily/docker/dynamic-example-information/lib/structure_definition.rb:130:in `mkdir'
/home/emily/docker/dynamic-example-information/lib/structure_definition.rb:130:in `write_example'
/home/emily/docker/dynamic-example-information/lib/fhir_gen.rb:20:in `block (2 levels) in run'
/home/emily/docker/dynamic-example-information/lib/fhir_gen.rb:17:in `times'
/home/emily/docker/dynamic-example-information/lib/fhir_gen.rb:17:in `block in run'
/home/emily/docker/dynamic-example-information/lib/fhir_gen.rb:15:in `each'
/home/emily/docker/dynamic-example-information/lib/fhir_gen.rb:15:in `run'
/home/emily/docker/dynamic-example-information/lib/tasks.rake:31:in `block (2 levels) in <top (required)>'
/usr/share/gems/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
Tasks: TOP => fhir_gen:run
(See full trace by running task with --trace)
[emily@delli5 dynamic-example-information]$ ls -ltr
total 20
-rw-rw-r--. 1 emily emily   63 Apr 22 15:21 Gemfile
-rw-rw-r--. 1 emily emily   47 Apr 22 15:21 Rakefile
-rw-rw-r--. 1 emily emily  375 Apr 22 15:21 Gemfile.lock
-rw-rw-r--. 1 emily emily 2166 Apr 25 10:10 README.md
drwxrwxr-x. 5 emily emily 4096 Apr 25 10:10 lib

[emily@delli5 dynamic-example-information]$ mkdir examples
[emily@delli5 dynamic-example-information]$ rake fhir_gen:run[uscore,2,max]

Generating 60 examples across 30 uscore resources using max cardinality strategy...
us-core-pulse-oximetry (2/2)
rake aborted!
Errno::ENOENT: No such file or directory @ dir_s_mkdir - log/uscore
/home/emily/docker/dynamic-example-information/lib/structure_definition.rb:151:in `mkdir'
/home/emily/docker/dynamic-example-information/lib/structure_definition.rb:151:in `write_failure_log'
/home/emily/docker/dynamic-example-information/lib/fhir_gen.rb:23:in `block in run'
/home/emily/docker/dynamic-example-information/lib/fhir_gen.rb:15:in `each'
/home/emily/docker/dynamic-example-information/lib/fhir_gen.rb:15:in `run'
/home/emily/docker/dynamic-example-information/lib/tasks.rake:31:in `block (2 levels) in <top (required)>'
/usr/share/gems/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
Tasks: TOP => fhir_gen:run
(See full trace by running task with --trace)
[emily@delli5 dynamic-example-information]$ mkdir log

6. Able to run the script without error after manually creating examples and log dirs:
[emily@delli5 dynamic-example-information]$ rake fhir_gen:run[uscore,2,max]

**Comment by higgins777** [comment]
Pushed this change.
